//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLTWarter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class DeploymentSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DeploymentSettings defaultInstance = ((DeploymentSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DeploymentSettings())));
        
        public static DeploymentSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zh-CN")]
        public global::System.Globalization.CultureInfo Locale {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Locale"]));
            }
            set {
                this["Locale"] = value;
            }
        }
    }
}
