//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLTWarter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class DeploymentSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DeploymentSettings defaultInstance = ((DeploymentSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DeploymentSettings())));
        
        public static DeploymentSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintLabelServer {
            get {
                return ((string)(this["PrintLabelServer"]));
            }
            set {
                this["PrintLabelServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintLabelQueue {
            get {
                return ((string)(this["PrintLabelQueue"]));
            }
            set {
                this["PrintLabelQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintLabelSettings {
            get {
                return ((string)(this["PrintLabelSettings"]));
            }
            set {
                this["PrintLabelSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintLabelIsEnable {
            get {
                return ((bool)(this["PrintLabelIsEnable"]));
            }
            set {
                this["PrintLabelIsEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintReportServer {
            get {
                return ((string)(this["PrintReportServer"]));
            }
            set {
                this["PrintReportServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintReportQueue {
            get {
                return ((string)(this["PrintReportQueue"]));
            }
            set {
                this["PrintReportQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintReportSettings {
            get {
                return ((string)(this["PrintReportSettings"]));
            }
            set {
                this["PrintReportSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintReportIsEnable {
            get {
                return ((bool)(this["PrintReportIsEnable"]));
            }
            set {
                this["PrintReportIsEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Summary")]
        public string PrintReportMode {
            get {
                return ((string)(this["PrintReportMode"]));
            }
            set {
                this["PrintReportMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintBigLabelServer {
            get {
                return ((string)(this["PrintBigLabelServer"]));
            }
            set {
                this["PrintBigLabelServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintBigLabelQueue {
            get {
                return ((string)(this["PrintBigLabelQueue"]));
            }
            set {
                this["PrintBigLabelQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintBigLabelSettings {
            get {
                return ((string)(this["PrintBigLabelSettings"]));
            }
            set {
                this["PrintBigLabelSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintBigLabelIsEnable {
            get {
                return ((bool)(this["PrintBigLabelIsEnable"]));
            }
            set {
                this["PrintBigLabelIsEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zh-CN")]
        public global::System.Globalization.CultureInfo Locale {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Locale"]));
            }
            set {
                this["Locale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomizationVersion {
            get {
                return ((string)(this["CustomizationVersion"]));
            }
            set {
                this["CustomizationVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Customization {
            get {
                return ((string)(this["Customization"]));
            }
            set {
                this["Customization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PrintLabelLeftPadding {
            get {
                return ((double)(this["PrintLabelLeftPadding"]));
            }
            set {
                this["PrintLabelLeftPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PrintLabelRightPadding {
            get {
                return ((double)(this["PrintLabelRightPadding"]));
            }
            set {
                this["PrintLabelRightPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MergingContextSelectedColumns {
            get {
                return ((string)(this["MergingContextSelectedColumns"]));
            }
            set {
                this["MergingContextSelectedColumns"] = value;
            }
        }
    }
}
