//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLTWarter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLTWarter.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        internal static string dateEventConvention {
            get {
                return ResourceManager.GetString("dateEventConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy年M月d日 (ddd) HH:mm.
        /// </summary>
        internal static string dateEventLongConvention {
            get {
                return ResourceManager.GetString("dateEventLongConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建立站点成功。.
        /// </summary>
        internal static string msgStationCreated {
            get {
                return ResourceManager.GetString("msgStationCreated", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream soundDing {
            get {
                return ResourceManager.GetStream("soundDing", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream soundMismatch {
            get {
                return ResourceManager.GetStream("soundMismatch", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream soundSelected {
            get {
                return ResourceManager.GetStream("soundSelected", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream soundWeight {
            get {
                return ResourceManager.GetStream("soundWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编码最少长一个字、最长三十个字、且不能含有特殊符号或空格.
        /// </summary>
        internal static string validationBarcodeForSearchInvalid {
            get {
                return ResourceManager.GetString("validationBarcodeForSearchInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能为空.
        /// </summary>
        internal static string validationEmptyPassword {
            get {
                return ResourceManager.GetString("validationEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 两次输入密码不一致.
        /// </summary>
        internal static string validationPasswordConfirmMismatch {
            get {
                return ResourceManager.GetString("validationPasswordConfirmMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能少于四位.
        /// </summary>
        internal static string validationPasswordTooShort {
            get {
                return ResourceManager.GetString("validationPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 别名不能包含特殊符号或空格.
        /// </summary>
        internal static string validationShipmentAlias {
            get {
                return ResourceManager.GetString("validationShipmentAlias", resourceCulture);
            }
        }
    }
}
