//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLTWarter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLTWarter.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string converterEntityRolesMap {
            get {
                return ResourceManager.GetString("converterEntityRolesMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}路.
        /// </summary>
        internal static string converterRouteCacheNewRoute {
            get {
                return ResourceManager.GetString("converterRouteCacheNewRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string converterRouteName {
            get {
                return ResourceManager.GetString("converterRouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        internal static string dateEventConvention {
            get {
                return ResourceManager.GetString("dateEventConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy年M月d日 (ddd) HH:mm.
        /// </summary>
        internal static string dateEventLongConvention {
            get {
                return ResourceManager.GetString("dateEventLongConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel的工作表中数据少于两行，未能合并。.
        /// </summary>
        internal static string excelExportMergeWorksheetInvalidFormat {
            get {
                return ResourceManager.GetString("excelExportMergeWorksheetInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未能打开Excel中的工作表。.
        /// </summary>
        internal static string excelExportMergeWorksheetMissing {
            get {
                return ResourceManager.GetString("excelExportMergeWorksheetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM/dd HH:mm:ss.
        /// </summary>
        internal static string exportDateFormat {
            get {
                return ResourceManager.GetString("exportDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存档时出现以下错误，请再试一次：{0}.
        /// </summary>
        internal static string exportError {
            get {
                return ResourceManager.GetString("exportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户创建成功.
        /// </summary>
        internal static string msgCustomerCreated {
            get {
                return ResourceManager.GetString("msgCustomerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户修改成功.
        /// </summary>
        internal static string msgCustomerModified {
            get {
                return ResourceManager.GetString("msgCustomerModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel文件 (*.xls;*.xlsx)|*.xls;*.xlsx|所有文件|*.*.
        /// </summary>
        internal static string msgFileDialogExcelFileFilter {
            get {
                return ResourceManager.GetString("msgFileDialogExcelFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归班完成！.
        /// </summary>
        internal static string msgFinishCheckinComplete {
            get {
                return ResourceManager.GetString("msgFinishCheckinComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单添加成功。.
        /// </summary>
        internal static string msgOrderCreated {
            get {
                return ResourceManager.GetString("msgOrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建立产品成功。.
        /// </summary>
        internal static string msgProductCreated {
            get {
                return ResourceManager.GetString("msgProductCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建立站点成功。.
        /// </summary>
        internal static string msgStationCreated {
            get {
                return ResourceManager.GetString("msgStationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建用户成功.
        /// </summary>
        internal static string msgUserCreated {
            get {
                return ResourceManager.GetString("msgUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户保存成功.
        /// </summary>
        internal static string msgUserModified {
            get {
                return ResourceManager.GetString("msgUserModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格兰特.
        /// </summary>
        internal static string ProductNameLong {
            get {
                return ResourceManager.GetString("ProductNameLong", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream soundDing {
            get {
                return ResourceManager.GetStream("soundDing", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream soundMismatch {
            get {
                return ResourceManager.GetStream("soundMismatch", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream soundSelected {
            get {
                return ResourceManager.GetStream("soundSelected", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream soundWeight {
            get {
                return ResourceManager.GetStream("soundWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编码最少长一个字、最长三十个字、且不能含有特殊符号或空格.
        /// </summary>
        internal static string validationBarcodeForSearchInvalid {
            get {
                return ResourceManager.GetString("validationBarcodeForSearchInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能为空.
        /// </summary>
        internal static string validationEmptyPassword {
            get {
                return ResourceManager.GetString("validationEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要导出的字段。.
        /// </summary>
        internal static string validationExportMergeColumnEmpty {
            get {
                return ResourceManager.GetString("validationExportMergeColumnEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要合并的Excel文件。.
        /// </summary>
        internal static string validationExportMergeDataExcelEmpty {
            get {
                return ResourceManager.GetString("validationExportMergeDataExcelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请以毫米为单位输入边距。输入的数字要等于或大于零。.
        /// </summary>
        internal static string validationInvalidLabelPadding {
            get {
                return ResourceManager.GetString("validationInvalidLabelPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归班金额与订单价值不符(订单金额：{0}，归班金额：{1})，是否继续归班？.
        /// </summary>
        internal static string validationPaperReturnValueError {
            get {
                return ResourceManager.GetString("validationPaperReturnValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 两次输入密码不一致.
        /// </summary>
        internal static string validationPasswordConfirmMismatch {
            get {
                return ResourceManager.GetString("validationPasswordConfirmMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能少于四位.
        /// </summary>
        internal static string validationPasswordTooShort {
            get {
                return ResourceManager.GetString("validationPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 别名不能包含特殊符号或空格.
        /// </summary>
        internal static string validationShipmentAlias {
            get {
                return ResourceManager.GetString("validationShipmentAlias", resourceCulture);
            }
        }
    }
}
